# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "voiceyourplace-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-112060364-2"

menu:
  - { name: "Curtea de Argeș", url: "audio-ghid" }
  - { name: "Audio ghid", url: "audio-ghid" }
  - { name: "Comunitate", url: "comunitate" }
  - { name: "Proiect", url: "proiect" }
  - { name: "Contact", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "instagram", link: "https://instagram.com/voiceyourplace", title: "INSTAGRAM", image: "logo-instagram.svg" }
  - { icon: "facebook", link: "https://facebook.com/voiceyourplace", title: "FACEBOOK", image: "logo-facebook.svg" }
  - { icon: "soundcloud", link: "https://soundcloud.com/voice-your-place", title: "SOUNDCLOUD", image: "logo-soundcloud.svg" }
  - { icon: "youtube", link: "https://www.youtube.com/@VoiceYourPlace", title: "YOUTUBE", image: "logo-youtube.svg" }

social-partners:
  - { name: "OAR", image: "oar-logo.svg" }
  - { name: "Partners & Sponsors", image: "partners-sponsors.svg" }
  - { name: "CJA", image: "cj-arges-logo.svg" }

community:
  - { front: "comunitate-front-1.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-2.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-3.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-4.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-5.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-6.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-7.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-8.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-9.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-10.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-11.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-12.svg", back: "comunitate-back-1.svg", url: "comunitate" }
  - { front: "comunitate-front-13.svg", back: "comunitate-back-1.svg", url: "comunitate" }


# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
