# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "voiceyourplace-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-112060364-2"

menu:
  - { name: "Curtea de Arges", url: "curtea-de-arges" }
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "facebook", link: "facebook.com/voiceyourplace" }
  - { icon: "instagram", link: "instagram.com/voiceyourplace" }
  - { icon: "youtube", link: "https://www.youtube.com/@VoiceYourPlace" }
  - { icon: "envelope", link: "voiceyourplace@gmail.com" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
