# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "voiceyourplace-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-112060364-2"

menu:
  - { name: "Curtea de Arges", url: "audio-ghid" }
  - { name: "Audio ghid", url: "audio-ghid" }
  - { name: "Comunitate", url: "comunitate" }
  - { name: "Proiect", url: "proiect" }
  - { name: "Contact", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "instagram", link: "https://instagram.com/voiceyourplace", title: "INSTAGRAM", image: "logo-instagram.svg", image-bar: "logo-bar-instagram.svg" }
  - { icon: "facebook", link: "https://facebook.com/voiceyourplace", title: "FACEBOOK", image: "logo-facebook.svg", image-bar: "logo-bar-facebook.svg" }
  - { icon: "soundcloud", link: "https://soundcloud.com/voice-your-place", title: "SOUNDCLOUD", image: "logo-soundcloud.svg", image-bar: "logo-bar-soundcloud.svg" }
  - { icon: "youtube", link: "https://www.youtube.com/@VoiceYourPlace", title: "YOUTUBE", image: "logo-youtube.svg", image-bar: "logo-bar-youtube.svg" }
  # - { icon: "envelope", link: "voiceyourplace@gmail.com" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
